### ISSUE TITLE
feat: Alternative Plugin Shortname Repo

### ISSUE THREAD

**Issue by Hypnotist1148** [jdxcode/rtx#163]
By default RTX uses ASDF's Plugin Catalog, would it be viable to add a global config option to add multiple plugin catalogs or even disable the default one?
This would be a huge plus for oranisations using rtx.

## Global Config TOML Example
```toml
# To enable/disable the default catalog
use_default_plugin_catalog = true

# Sorted list of Git Repo URLs
custom_plugin_catalogs = [ "https://mygit....", "ssh://git@mygit..." ] 
```

## Logic
The order of search should be `https://mygit....` > `ssh://git@mygit...`>`default-catalog`

## Example using .tool-version
There could also be a option to link a git repo instead of a plugin name like this:
```txt
repo:https://mygit.../java|ssh://mygit.../java prefix:adoptopenjdk-17
```
