### ISSUE TITLE
feat: rtx.plugin.toml

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/rtx#328]
I think we should add a plugin config toml file. This could be useful for putting in configuration so that we don't need to launch bash to get things like `bin/list-aliases` and stuff. This will make rtx faster since the biggest bottleneck by far is launching bash for these things.

They're generally always cached, but that logic may not work well for every plugin. I would much rather use declarative config that doesn't require cache at all. This could also define the cache behavior for the different commands when bash is required. Here's roughly what I'm thinking this would look like:

```toml
[list-legacy-filenames]
# "data" means use this data instead of executing the script
data = ['.node-version', '.nvmrc']
[exec-env]
# cache the results of `bin/exec-env` so long as these env vars haven't changed
cache-key = "{{env.PWD}}-{{env.TOOL_OPTS__VIRTUAL_ENV}}"
cache-duration = '1 hour' # recache after some time
cache = true # set to false to disable cache entirely (and make rtx much slower)
[list-aliases.data]
lts = '18'
'lts/hydrogen' = '18'
'lts/gallium' = '16'
```

The templating for things like the cache-key could be done with handlebars or [tera](https://tera.netlify.app/docs).

I think later down the road we could make these proper formulas that could be used like this:

```toml
type = 'github-releases'
bin = 'bin/some-tool' # location inside of tarball

[list-all]
github = 'jdxcode/some-tool'

[source]
url = 'https://github.com/jdxcode/some-tool/archive/refs/tags/v{{version}}.tar.gz'

[build]
script = """
make PREFIX={{prefix}} install
"""

[test]
script = """
some-tool --version
"""

# this will be hard, but I would like to get here
[dependencies]
java = '17'
[build-dependencies]
cmake = 'latest'
```

Then you wouldn't need _any_ `bin/install`, `bin/list-all` scripts or anything. Aside from making it easy to author plugins, there are security reasons why I want to do this since it makes it easier for me to do hash checking if the plugins don't do the downloading inside of bash scripts.

Another thing I want to do in the future is support some kind of precompiled binary setup sort of like homebrew's bottles. I'm tired of waiting for Python to compile. I could use some existing precompiled Python binaries maybe, but I want to explore the idea of having rtx be capable of generating shared binaries somehow.

I'm going to kick this one around in my brain a bit.

Related:
* https://github.com/smashedtoatoms/asdf-postgres/issues/68
* #321
