### ISSUE TITLE
Loading env variables from .env file

### ISSUE THREAD

**Issue by delicb** [jdxcode/rtx#331]
`rtx` supports `env` table in `.rtx.toml`, which is awesom. One step closer to replacing `direnv` would be adding support to load environment variables from `.env` file (in addition to defining them in `.rtx.toml`). 

I like having them in `.env`, since there are situation when process is started without shell context (e.g. some IDE debuggers) and in those cases some applications know how to load `.env` (e.g. https://github.com/grauwoelfchen/flask-dotenv/). 

What I would like is config flag that works along the lines of `direnv` [dotenv_if_exists](https://github.com/direnv/direnv/blob/master/stdlib.sh#L248) stdlib function. That way, env variables are maintained only in one place.

Is this something that you see being in scope of the project and would consider adding to `rtx`?

**Comment by jdxcode** [comment]
this was something I originally planned to do, you can see it mentioned in the PR: https://github.com/jdxcode/rtx/pull/241

However I didn't add it since I didn't love the syntax. I had 3 different ideas on how to configure it:

```toml
[env]
env_file = '.env' # as a pseudo-env var, this would prevent you from using "env_file" as a key though
```

```toml
env = '.env' # as an override, this would prevent you from having keys in .env _and_ in .rtx.toml, but I think it's clean
```

```toml
env_file = '.env' # as a separate key
[env]
FOO = 'bar'
```

I'm leaning towards the last one, however I think you need to really understand TOML in that case since `env_file` would need to be at the very top of the file. It might be confusing to newer developers why this is invalid:

```toml
[tools]
python = '3.10'

env_file = '.env'
[env] FOO = 'bar'
```

Right now I like that we have no top-level keys for this reason.
