### ISSUE TITLE
Ability to not touch GOPATH and GOROOT at all

### ISSUE THREAD

**Issue by scop** [jdxcode/rtx#754]
I'd like to see a way to use rtx with its built in Go plugin so that it never touches the `$GOPATH` and `$GOROOT` at all.

Currently, it's possible to set these to some values in the "pristine" env and rtx won't overwrite them, but what I'm (additionally) after is that they would not be set to anything even if they're unset.

The rationale for this is that just the `go` executable in `$PATH` is enough for the common use case; Go's defaults kick in without `$GOPATH` and `$GOROOT` in env, and make sense for a lot of setups, and match Go's docs. Those two complicate things, and bear risk of misconfiguration.

There's some discussion in asdf-land which has the same problems, some progress albeit slow:
- https://github.com/asdf-community/asdf-golang/pull/80
- https://github.com/asdf-community/asdf-direnv/issues/149

For asdf, I have a workaround as described in https://github.com/asdf-community/asdf-direnv/issues/149#issuecomment-1107429996, but for rtx, I haven't found a good one.
```toml
[env]
GOPATH = "/my/home/dir/go" # works, prevents being overwritten on switch, but I'd rather not have it set at all
GOROOT = false # does not prevent being set by the plugin; setting is mostly harmless but unnecessary, I'd rather not have it set at all

[tools]
go = "1.20.6"
```

I guess at least either of these would work UX-wise:
- Setting those two to `false` in `[env]`, or
- Using let's say `go = {version="1.20.6", env_path_only=true}` to cause the plugin to only set `$PATH` (only the go/bin dir would be needed there, packages/ could be entirely forgotten about in this setup)
